version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update -y
            sudo apt install awscli -y
      - run:
          name: Deploy to S3
          command: aws s3 sync build s3://$S3_BUCKET_NAME
